### ISSUE TITLE
[Bug] Not able to locate the shadow element

### ISSUE THREAD

**Issue by mohammedalnuaimi** [abramenal/cypress-shadow-dom#10]
### Current behavior:
I don't seem to be able to locate the elements inside
Cypress keeps throwing the following error
[cypress-shadow-dom error]: Error: element not found.
Check provided lookup conditions

the root element gets located, however the ShadowFind() fails when trying to locate the child node in the shadow DOM

not found.

logError @ cypress_runner.js:157775
(anonymous) @ cypress_runner.js:157448
emit @ cypress_runner.js:121451
(anonymous) @ cypress_runner.js:101926
emit @ cypress_runner.js:121451
emit @ cypress_runner.js:101958
_onErrorClick @ cypress_runner.js:100849
(anonymous) @ cypress_runner.js:102077
executeAction @ cypress_runner.js:141107
res @ cypress_runner.js:141098
ca @ cypress_runner.js:149113
ja @ cypress_runner.js:149114
ka @ cypress_runner.js:149114
wa @ cypress_runner.js:149116
Aa @ cypress_runner.js:149117
ya @ cypress_runner.js:149117
Da @ cypress_runner.js:149120
Ad @ cypress_runner.js:149183
Gi @ cypress_runner.js:149349
Kb @ cypress_runner.js:149138
Dd @ cypress_runner.js:149185
(anonymous) @ cypress_runner.js:149350
./node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority @ cypress_runner.js:152175
Ii @ cypress_runner.js:149350
Cd @ cypress_runner.js:149184

### Desired behavior:
I should be able to locate the elements within the shadow dom using this extended feature

when writing the test scenario using the following DOM extended method
like the following:

### Steps to reproduce: (app code and test code)

 cy.visit('/pagename')
            cy.shadowGet('login-page')
            .shadowFind('.login-button')
            .shadowTrigger('click')

### Versions
"cypress": "^3.3.1",
"cypress-shadow-dom": "^1.0.0",

Macbook Pro

**Comment by mohammedalnuaimi** [comment]
@abramenal  will those shadow methods works only with non class, non id elements like the ones in your example https://github.com/abramenal/cypress-shadow-dom/blob/master/example/cypress/integration/todolist.spec.js

**Comment by sarafs** [comment]
Hello @abramenal , I am facing the same issue as detailed above. 
All the elements on the webpage have a class or an id.
When I do something like this 
cy.visit('url');
    cy.expect('#element id').to.exist;
    cy.shadowGet('.element class')
        .shadowFind('.element class')
        .shadowContains('content text');

Cypress passes for the first 3 steps i.e. cy.visit, cy.expect, cy.shadowGet
But fails for cy.shadowFind & cy.shadowContains
with TypeError: Cannot read property 'shadowRoot' of undefined for cmd `npx cypress run`

On `npx cypress open` it fails with TypeError: Cannot read property 'shadowRoot' of undefined on first run, however if I delete a space on the test_spec.js and save it as the Cypress Test Runner is running, it passes 2nd time round. 
This is not useful for running the tests in CI Jenkins. 
Not sure how to get around this.

**Comment by mohammedalnuaimi** [comment]
hey @abramenal  just to update you on this issue, I think it's not your solution issue, it's Cypress issue that will prevent us making a request from within iframe to another site, which will eventually  block the call
I've tried your solution with your example with another solution and it worked, but it didn't work with my app, as we use Auth0 to login first

**Comment by sarafs** [comment]
I have managed to get around the `TypeError: Cannot read property 'shadowRoot' of undefined` error on the `run` cmd by reloading the page again.
i.e. 
cy.visit('url');
cy.reload();

**Comment by abramenal** [comment]
Hi @mohammedalnuaimi 
Thanks for submitting the issue!

I think what you are doing is related to https://en.wikipedia.org/wiki/Same-origin_policy
Can you please share how does that work if you're trying to query regular DOM elements inside iframe?
It is likely will be an enhancement PR to support that case.

**Comment by abramenal** [comment]
@sarafs hey there!
Could you please share some details of your setup and test code? It seems something is wrong so let's take a look if you haven't fixed that issue (`cy.reload()` is not a good one I think).

**Comment by mohammedalnuaimi** [comment]
Thanks @abramenal  yes I was trying to make a call from within cypress iframe against another origin which was getting rejected
your solution works well but not with our case, I actually ended up using puppeteer due to this issue
Thanks for your help

**Comment by abramenal** [comment]
This might be the possible solution
https://github.com/cypress-io/cypress/issues/136#issuecomment-525994895

But anyway thanks for the feedback @mohammedalnuaimi!
