### ISSUE TITLE
[Bug] shadowFind doesn't work with using a space in an attribute selector

### ISSUE THREAD

**Issue by joshuadelange** [abramenal/cypress-shadow-dom#11]
Thank you for the great plugin!

### Current behavior:

I want to find a shadow element where its placeholder attributer is "First Name", but it's failing with the error:

> [cypress-shadow-dom error]: Selector must be single.
> In case if you need multiple please chain it with .shadowFind() command

<img width="458" alt="Screenshot 2019-10-10 at 14 35 18" src="https://user-images.githubusercontent.com/525349/66569127-2ff31a80-eb6b-11e9-9bc7-23908e2f9f03.png">

### Desired behavior:

The element to be found.

### Steps to reproduce: (app code and test code)

Have a shadow element with a placeholder attribute with a space in its value.

Then trying to find it it with;
`
cy.shadowGet('lightning-input').shadowFind('input[placeholder="First Name"]').shadowType('123123123')
`

### Versions

Cypress 3.4.1,  macOS 10.14.5, Chrome 77.0.3865.90

Thank you!

**Comment by abramenal** [comment]
Hi @joshuadelange 
Thanks for submitting the issue!

This is a good catch and I'll review this during the weekend. Will let you know 🥂

**Comment by abramenal** [comment]
Hi @joshuadelange,
v1.0.1 is out containing the fix!
Thanks for submitting the issue again.

**Comment by joshuadelange** [comment]
Thank you @abramenal , it works great!

**Comment by abramenal** [comment]
@all-contributors please add @joshuadelange for bug

**Comment by abramenal** [comment]
@all-contributors please add @joshuadelange for bug
