### ISSUE TITLE
[Bug] Implementing cypress-shadow-dom as typescript

### ISSUE THREAD

**Issue by arielazzi** [abramenal/cypress-shadow-dom#13]
### Description
we're implementing `cypress-shadow-dom` in our project, but we also use Cypress with Typescript. We tried to add the package with the following statement, but it didn't work: 

```ts
/// <reference path="../node_modules/cypress-shadow-dom/index.d.ts" />
```
Could you please advise us on how to implement it?

**Comment by abramenal** [comment]
Hi @arielazzi 
Thanks for submitting the issue.
Seems it should work if you use it like you've described:
https://github.com/cypress-io/cypress-xpath/pull/16/files

Have you tried setting the path to `/// <reference path="cypress-shadow-dom" />`?

**Comment by arielazzi** [comment]
Hi @abramenal 
Thank you so much for your fast response!
we tried to implement your suggestion, but it didn't work. Could you please clarify your answer?

Thanks

**Comment by abramenal** [comment]
Hi @allout58 
You was doing this MR: https://github.com/abramenal/cypress-file-upload/pull/5
I am curious if you know anything that could help @arielazzi about how exactly you incorporate custom command typings into your project.
Much appreciated!! 🙏

**Comment by allout58** [comment]
@abramenal I can add some typings when I get a chance, might be a few days though.
@arielazzi If you look at the PR in the comment above, you can get an idea of how to add in the typings yourself if you need it sooner

**Comment by allout58** [comment]
Whoops, I didn't see you already had typings. I can take a look, but I'm not sure if I can be all that helpful :frowning:

**Comment by allout58** [comment]
I was able to get it to work as is, but I added `cypress-shadow-dom` to the `types` array in `tsconfig.json` instead of your reference version.
@arielazzi What version of TS are you using?

**Comment by allout58** [comment]
Ahha! According to the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-) you have to change it to `/// <reference *types*="cypress-shadow-dom">`. It also says to not use the reference method unless you are writing a `.d.ts` by hand, but to [use the method I mentioned above instead](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types)
