### ISSUE TITLE
[Bug] - retry-ability with dynamically added elements is not working

### ISSUE THREAD

**Issue by DesignByOnyx** [abramenal/cypress-shadow-dom#30]
### Current behavior:

Recent changes caused a regression as described in this comment: https://github.com/abramenal/cypress-shadow-dom/issues/25#issuecomment-568900779

### Desired behavior:

The previously working example should be fixed.

**Comment by abramenal** [comment]
@DesignByOnyx 
Thanks again for your contribution!
I've released all your changes in `v1.3.0`.
