### ISSUE TITLE
shadowFind works with cypress runner but doesn't work when run in the command line

### ISSUE THREAD

**Issue by shinjji** [abramenal/cypress-shadow-dom#36]
I'm using shadowFind in a test:
cy.shadowGet('.ui-widget')
          .shadowFind('.logo-wrapper')
          .shadowContains('logoText')
It works fine when using the cypress runner but when I try 'cypress run' to run it in the command line it doesn't work:
CypressError: Timed out retrying: Expected to find element: 'undefined', but never found it.

Am I doing something incorrectly?

Thanks!

**Comment by abramenal** [comment]
Hi @shinjji 
Thanks for submitting the issue.

It is fixed with latest v1.4.0 release
