### ISSUE TITLE
shadowEq method enhancement

### ISSUE THREAD

**Issue by mksjha** [abramenal/cypress-shadow-dom#42]
### Current behavior:

shadowEq returns the nth element from found shadow DOM collection

### Desired behavior:

Could we please have option to pass text in shadoweq method so it will return the element having that text from collection? We are using this method to select data from dropdown, If some value is added or deleted from dropdown collection, test fails as it is unable to find that option in that position. If we can select value of dropdown by passing text, it will always find tat option and addition/deletion dropdown data will not cause test failure.

**Comment by abramenal** [comment]
Hi @mksjha 
Thanks for submitting the issue.
You can use `shadowContains` for that.
