### ISSUE TITLE
Cypress 4.x.x support?

### ISSUE THREAD

**Issue by ChengJiaLiang** [abramenal/cypress-shadow-dom#45]
Versions Support

Will current Cypress-Shadow-Dom version 1.3.0 support Cypress 4.x.x?

Thanks

**Comment by abramenal** [comment]
Hi @ChengJiaLiang 
Thanks for submitting the issue!
I think right now nothing blocks of using v4 Cypress, can you please update this line
https://github.com/abramenal/cypress-shadow-dom/blob/master/package.json#L34
with something like:
`"cypress": ">3.0.0"`
